### ISSUE TITLE
Issue of plot interpretation in Roth 2024 

### ISSUE THREAD

**Issue by Alalalalaki** [lsun20/EventStudyInteract#11]
Hi,

I recently learned from [Roth 2024](https://www.jonathandroth.com/assets/files/HetEventStudies.pdf) that the default plots by recent methods (de Chaisemartin and D’Haultfuille, 2020; Callaway and SantAnna, 2021; Borusyak, Jaravel and Spiess, 2024) do not match those of traditional (TWFE) event-studies. And it is suggested adding long2 when using CS/dCDH packages.

I just wonder that is the estimator here also subject to similar issues? And does the default setting of EventStudyInteract provide event study plots comparable to TWFE? 

Thanks!

**Comment by lsun20** [comment]
Thank you for sharing the note by Roth (2024)!  This estimator collapses to the TWFE in the non-staggered case, which was illustrated [in the replication code](https://github.com/jonathandroth/HetEventStudies/blob/ad5eb977345f9f4c539fc63bdd5e8a1362f4222b/EvaluateEventPlots.R#L83) of Roth (2024).  For the Stata version eventstudyinteract, you need to manually specify relative time indicators as you would have included in the TWFE, and usually that means leaving out the -1 relative period in the non-staggered case.
